### ISSUE TITLE
src/Mesh/EBC_Partition_turbulence_wall_model.cpp 的改进

### ISSUE THREAD

**Issue by ju-liu** [APSIS-ANALYSIS/PERIGEE#151]
该文件中第21行的if如果没有满足条件是否应该报错？

或者说我们能否确信ALocal_WeakBC中get函数的取值范围是0到get_num_ele?

**Comment by Goldeninscriptions** [comment]
WeakBC的剖分还是延续以往的ebc的习惯，用的是体网格的part，没有用metis额外对wall单独剖分。

17行到26行到for循环到意思是：每个cpu对于wall上的所有单元，试探性看看这个单元在不在自己存储的体网格里。如果在的话就存一下它在本cpu的体网格里排第几个（part_vol_ele_id）以及face_id，如果不在就不在（在别的cpu里）。

最后每个cpu或许分到了wall的一部分，或许一个wall单元都没分到（全看体网格是怎么分的），然后再定下每个cpu上的num_ele是那一部分的单元个数（根据已有的ebc函数，就是num_local_cell)。
