### ISSUE TITLE
Accelerate the preprocess procedure by parallelization

### ISSUE THREAD

**Issue by ju-liu** [APSIS-ANALYSIS/PERIGEE#33]
In at least two parts, the procedure can be accelerated by an OpenMP type parallelization:

1. In the convection from gmsh to vtu, the loop over element can be parallelized;
2. In the partition of the mesh file, the generation of part file can be parallelized.

**Comment by ZhaoChongran** [comment]
I have parallelize part of following functions in a new branch `[openmp-dev-linux]` of repo called `M3C-Lab/PERIGEE-viv2022`:

- `GmshFIleIO::write_vtp()` in `M3C-Lab/PERIGEE-viv2022/src/Mesh/`
-  `GmshFileIO::write_each_vtu()` in `M3C-Lab/PERIGEE-viv2022/src/Mesh/`
- `Part_Tet::Generate_Partition()` in `M3C-Lab/PERIGEE-viv2022/src/Mesh/`
- `NodalBC_3D_FSI::NodalBC_3D_FSI()` in `M3C-Lab/PERIGEE-viv2022/examples/tet4_fsi/src/` 
- `NodalBC_3D_vtu::NodalBC_3D_vtu()` in `M3C-Lab/PERIGEE-viv2022/src/Mesh/`.

**Comment by ju-liu** [comment]
- [ ] openmp的计时功能
- [ ] openmp的配置
- [ ] openmp的报错信息处理

**Comment by ju-liu** [comment]
https://cliutils.gitlab.io/modern-cmake/chapters/packages/OpenMP.html

**Comment by ju-liu** [comment]
https://stackoverflow.com/questions/49816206/cmake-find-package-specify-path

**Comment by ju-liu** [comment]
https://stackoverflow.com/questions/56166109/detect-at-runtime-if-openmp-is-being-used-in-a-c-program

**Comment by ZhaoChongran** [comment]
使用cmake自带的FindOpenMP.cmake进行配置，在system_lib_loading.cmake内修改

- 添加：

```bash
set(OpenMP_ROOT /Users/chongran/lib/lib-omp)

find_package(OpenMP REQUIRED)

include_directories(${OpenMP_CXX_INCLUDE_DIR})

set(EXTRA_LINK_LIBS ${EXTRA_LINK_LIBS} ${OpenMP_CXX_LIBRARIES})

if(OPENMP_CXX_FOUND) 
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
endif()
```

- 修改：


```bash
if( ${CMAKE_BUILD_TYPE} MATCHES "Release" )
  set(CMAKE_CXX_FLAGS " -O3 -Wall ")
else( ${CMAKE_BUILD_TYPE} MATCHES "Release" )
  set(CMAKE_CXX_FLAGS " -DENABLE_TEST -O0 -Wall ")
endif( ${CMAKE_BUILD_TYPE} MATCHES "Release" )
```

变为

```bash
if( ${CMAKE_BUILD_TYPE} MATCHES "Release" )
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 -Wall ")
else( ${CMAKE_BUILD_TYPE} MATCHES "Release" )
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DENABLE_TEST -O0 -Wall ")
endif( ${CMAKE_BUILD_TYPE} MATCHES "Release" )
```

**Comment by ju-liu** [comment]
Conditional use of OpenMP

https://stackoverflow.com/questions/56717411/control-conditional-openmp-in-define-macro

**Comment by ju-liu** [comment]
https://stackoverflow.com/questions/45477355/difference-between-pragma-and-pragma-in-c

**Comment by ju-liu** [comment]
https://www.dealii.org/current/doxygen/deal.II/config_8h_source.html

**Comment by ju-liu** [comment]
我们或许可以调控对每个exeutable文件的编译flag，参考这个
https://stackoverflow.com/questions/24238937/how-to-change-a-compiler-flag-for-just-one-executable-in-cmake

@ZhaoChongran

**Comment by ju-liu** [comment]
[] 我们还需要在程序里面设置omp_num_threads，避免环境变量里面没有设置这个参数。

[] 我们需要在Sys_Tools中加入一个 print函数 能够把当前的线程个数打印出来。

@ZhaoChongran
