### ISSUE TITLE
Build "examples/tet4_vascular/FSI" with errors.

### ISSUE THREAD

**Issue by saitoasukakawaii** [APSIS-ANALYSIS/PERIGEE#39]
Dear all
I have tried to build the `examples/tet4_vascular/FSI` with cmake, but followed errors occur. 

`CMake Error at CMakeLists.txt:149 (ADD_LIBRARY):
  Cannot find source file:

    /home/shuoxing/software/PERIGEE/src/Mesh/IElemBC.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc

CMake Error at CMakeLists.txt:149 (ADD_LIBRARY):
  No SOURCES given to target: perigee_preprocess
`
I think the source file is missed.

Best

**Comment by ju-liu** [comment]
This example has been out-dated. Could you try PERIGEE/example/tet4_fsi, which is the current FSI code.
