### ISSUE TITLE
A linear elasticity code

### ISSUE THREAD

**Issue by ju-liu** [APSIS-ANALYSIS/PERIGEE#60]
For education purposes, we need to enable a linear elasticity example, preferably in the linearPDE folder.

**Comment by ju-liu** [comment]
@ZhaoChongran 你在yue-dev分支里面把linearPDE这个例子的openmp也配置好。

**Comment by ju-liu** [comment]
@SeaVegetable 把你的收敛性测试结果写到这里 备案。

**Comment by SeaVegetable** [comment]
[verification_elastodynamics.pdf](https://github.com/APSIS-ANALYSIS/PERIGEE/files/13258776/verification_elastodynamics.pdf)

**Comment by ju-liu** [comment]
> [verification_elastodynamics.pdf](https://github.com/APSIS-ANALYSIS/PERIGEE/files/13258776/verification_elastodynamics.pdf)

👍

**Comment by ju-liu** [comment]
@SeaVegetable 最后可以参考借鉴https://github.com/M3C-Lab/PERIGEE-tissue/blob/master/examples/tet4_seg_elastodynamics/src/VTK_Writer_Solids_Tet4.cpp
把柯西应力画出来。
