### ISSUE TITLE
ElemBC_3D_hex class in need

### ISSUE THREAD

**Issue by ju-liu** [APSIS-ANALYSIS/PERIGEE#65]
We will need a class to load hex mesh's boundary file for surface integral (Neuman BC).

In particular, we need to discuss a rule for the outward normal vector definition, and implement a reset IEN function for hex-quad mesh.

**Comment by Syj-0525** [comment]
我已经基于ElemBC_3D_tet类完成了ElemBC_3D类，里面包含了tet与hex，我已经在sun-dev分支上上传了修改，并完成了测试，测试是基于六面体单元组成的2个cube的fsi模型，测试时打印了边界每个单元的ien，并随机选取了边界每个单元上的点计算了单元的外法向量，检查打印信息后ien和外法向是计算无误的。对601单元的测试代码分别在PERIGEE/examples/test/sys_test.cpp与PERIGEE/examples/test/gmsh_test.cpp，对602单元的测试代码分别在PERIGEE/examples/test/sys_test2.cpp与PERIGEE/examples/test/gmsh_test2.cpp中
