### ISSUE TITLE
Unify print_fatal and print_exit

### ISSUE THREAD

**Issue by ju-liu** [APSIS-ANALYSIS/PERIGEE#75]
It is stupid to let the programmer decide which exit function to call. We should unify the way for aborting the program.

Petsc has a compiler directive that tells the code if PETSc is used or not. We could use it in the print_fatal funciton.

https://charlesreid1.com/wiki/Petsc

**Comment by ju-liu** [comment]
@Goldeninscriptions 等你休假回来后我们可以把这个任务了结了。当然，我们需要把所有的print_exit函数替换成print_fatal

**Comment by ju-liu** [comment]
https://stackoverflow.com/questions/8482651/how-do-i-conditionally-terminate-a-parallel-region-in-openmp

**Comment by ZhaoChongran** [comment]
Roger!

Ju Liu ***@***.***> 于2023年9月30日周六 10:34写道：
